library("readr")
ls("package:readr")
df1<-read_csv("retail_data.csv")
print(df1)

head(df1$Transaction_ID)
tail(df1$Transaction_ID)
str(df1)
summary(df1$Transaction_ID)
col(df1)
dim(df1)
mean(df1$Age)
age<-na.omit(df1$Age)
mean(age)
sum(is.na(df1$Age))
colSums(is.na(df1))
summary(df1$Age)
hist(df1$Age)       
df1$DoubleAge <- df1$Age * 2
head(df1$DoubleAge)
dim(df1)
View(df1)
wirte_csv(df1,"demo.csv", col_names=TRUE)
